---
title: "REPSWITCH1_Clean"
author: "Katerina Tsaroucha"
date: "2023-07-28"
output: html_document
---
```{r}
rm(list = ls())
```


```{r}
library(tidyverse)
library(readr)
library(readxl)
library(dplyr)
library(ggplot2)
```

```{r}
keyboard <- read.csv("C:\\Users\\Κατερίνα\\Nextcloud\\REPSWITCH_Analysis\\301023\\301023_REPSWITCH1_version1_list3_2023-10-30_10h16.57.694.csv", header = TRUE, sep = ";", encoding = "UTF-8") %>% 
  rename(Image = X.U.FEFF.image,
         RespModal = respModal,
         FrameColor = frameColor,
         RepSwitch = repSwitch,
         Trial_no = trial_no,
         CorrectAns = correctAns,
         SubjResponse = subjResponse,
         KeyResp_keys = keyResp.keys,
         KeyResp_rt = keyResp.rt,
         Target = target) %>% 
  select(-c(1, 16:52, 54, 57:71, 74:76)) %>% 
  filter(!row_number() %in% c(1, 2, 104)) %>% 
  relocate(Trial_no) %>% #move columns to the front
  relocate(SubjResponse, .after = CorrectAns) %>% 
  relocate(KeyResp_keys, .after = SubjResponse) %>% 
  relocate(KeyResp_rt, .after = KeyResp_keys) %>% 
  relocate(FrameColor, .after = RepSwitch) %>% 
  mutate(across(c("KeyResp_rt"), substr, 2, nchar(KeyResp_rt))) %>% #remove 1st char([) in the beginning of each string in the column
  mutate(KeyResp_rt = substr(KeyResp_rt, 1, nchar(KeyResp_rt)-1)) %>% #remove last char(]) in the beginning of each string in the column
  separate(KeyResp_rt, c("key1", "key2", "key3", "key4", "key5", "key6", "key7", "key8", "key9", "key10", "key11", "key12", "key13", "key14", "key15"), 
           ", ", extra = "merge", fill = "right") %>% #https://tidyr.tidyverse.org/reference/separate.html
  mutate(key1 = as.numeric(key1), key2 = as.numeric(key2), key3 = as.numeric(key3), key4 = as.numeric(key4),
         key5 = as.numeric(key5), key6 = as.numeric(key6), key7 = as.numeric(key7), key8 = as.numeric(key8),
         key9 = as.numeric(key9), key10 = as.numeric(key10), key11 = as.numeric(key11), key12 = as.numeric(key12),
         key13 = as.numeric(key13), key14 = as.numeric(key14), key15 = as.numeric(key15)
         ) %>% 
  mutate(Backspace = if_else(str_detect(KeyResp_keys, "backspace"), "1", "0")) %>% 
  relocate(Backspace, .after = SubjResponse) %>% 
  mutate(Item_correct = if_else(CorrectAns == SubjResponse & Backspace == "0", "1", "0")) %>% 
  relocate(Item_correct, .after = Backspace) %>% 
  relocate(RespModal, .after = Item_correct)

#write.csv(keyboard, "C:\\Users\\Κατερίνα\\Nextcloud\\REPSWITCH_Analysis\\301023\\keyboard_cleaned.csv", fileEncoding = "UTF-8")
```


```{r}
coded_keyboard <- read.csv("C:\\Users\\Κατερίνα\\Nextcloud\\REPSWITCH_Analysis\\301023\\301023_coded.csv", header = TRUE, sep = ";", encoding = "UTF-8") %>% 
  rename(Filename = X.U.FEFF.Filename) %>% 
  mutate(Trial_no = as.numeric(gsub(".*tr(\\d+).*", "\\1", Filename))) %>% 
  relocate(Trial_no) %>% 
  arrange(Trial_no)
```

```{r}
merged_keyboard <- merge(x = keyboard, y = coded_keyboard, by = "Trial_no", all = TRUE) %>% 
  select(-c(24:31, 34, 35)) %>% 
  rename(Duration = Duration..ms..#CorrectAns = CorrectAns.x,
         #SubjResponse = SubjResponse.x,
         #Backspace = Backspace.x,
         #RespModal = RespModal.x,
         #RepSwitch = RepSwitch.x,
         ) %>% 
  relocate(Item_correct, .after = Backspace) %>% 
  relocate(Modality_Correct, .after = Backspace) %>%
  #relocate(Error_Corrected, .after = Modality_Correct) %>% 
  relocate(Hesitation, .after = Item_correct) %>% 
  relocate(RT, .after = Hesitation) %>% 
  relocate(Duration, .after = RT) %>% 
  mutate(SubjResponse.x = ifelse(SubjResponse.x == "", SubjResponse.y, SubjResponse.x)) %>% 
  rename(SubjResponse = SubjResponse.x) %>% 
  relocate(Notes, .after = SubjResponse) %>%
  filter(!row_number() %in% c(102))
  #select(-c(33:39))

write.csv(merged_keyboard, "C:\\Users\\Κατερίνα\\Nextcloud\\REPSWITCH_Analysis\\301023\\301023_merged_coded.csv", fileEncoding = "UTF-8")
```













```{r}
pilot_data <- read.csv("D:\\GitHub\\experiment1\\Analysis\\pilot00\\pilot00_coded_updated.csv", header = TRUE, sep = ";"#, fileEncoding = "UTF-8"
                       ) %>%
  filter(Accuracy == 1) %>% 
  filter(RepSwitch %in% c("switch", "repeat"),
         respModal %in% c("speak", "type")) #%>% 
  #group_by(RepSwitch, respModal) %>% 
  #mutate(RT = as.numeric(RT))

write.csv(pilot_data, "D:\\GitHub\\experiment1\\Analysis\\pilot00\\pilot00_coded_clean.csv")
```

```{r}
data <- readxl::read_xlsx("D:\\GitHub\\experiment1\\Analysis\\pilot00\\pilot00_coded_updated.xlsx", sheet = 1) %>% 
  filter(Accuracy == 1) %>% 
  filter(RepSwitch %in% c("switch", "repeat"),
         respModal %in% c ("speak", "type")) %>% 
  mutate(RT = as.numeric(RT))
```

```{r}
ggplot(data, aes(x = RepSwitch, y = RT, fill = respModal)) +
  geom_bar(colour = "black", stat = "identity", width = 0.5, position = "dodge") +
  scale_fill_brewer(palette = "Set1") +
  labs(x ='Condition', y='Mean RTs (ms)', title = 'RTs of modality across conditions')

```


```{r}
speak <- readxl::read_xlsx("D:\\GitHub\\experiment1\\Analysis\\pilot00\\pilot00_coded_updated.xlsx", sheet = 1) %>% 
  filter(Accuracy == 1) %>% 
  filter(RepSwitch %in% c("switch", "repeat"),
         respModal %in% c ("speak")) %>% 
  mutate(RT = as.numeric(RT))
  #mutate(Condition = as.factor(Condition), 
         #Modality = as.factor(Modality))
```

```{r}
min(speak$RT)
max(speak$RT)
```


```{r}
#RT distribution, http://www.cookbook-r.com/Graphs/Plotting_distributions_(ggplot2)/
RTspeak <- ggplot(speak, aes(x = RT)) +
  geom_histogram(binwidth = 0.1,
                 colour = "black", fill = "white") +
  #geom_density(alpha = 0.2, fill = "#FF6666") + # Overlay with transparent density plot
  geom_vline(aes(xintercept = mean(RT, na.rm = T)),
             colour = "red", linetype = "dashed", size = 1) +
  xlab("RT speak (ms)") +
  ggtitle("RT distribution of Speak trials")

RTspeak
```

```{r}
#RT distribution, http://www.cookbook-r.com/Graphs/Plotting_distributions_(ggplot2)/
ggplot(data, aes(x = RT)) +
  geom_histogram(binwidth = 0.1,
                 colour = "black", fill = "white") +
  #geom_density(alpha = 0.2, fill = "#FF6666") + # Overlay with transparent density plot
  geom_vline(aes(xintercept = mean(RT, na.rm = T)),
             colour = "red", linetype = "dashed", size = 1) + facet_wrap(~respModal)+
  xlab("RT (ms)") +
  ggtitle("RT distribution")

ggplot(data, aes(x = RT)) +
  geom_histogram(binwidth = 0.1,
                 colour = "black", fill = "white") +
  #geom_density(alpha = 0.2, fill = "#FF6666") + # Overlay with transparent density plot
  # geom_vline(aes(xintercept = mean(RT, na.rm = T)),
             # colour = "red", linetype = "dashed", size = 1) + 
  facet_grid(rows = vars(respModal), cols = vars(RepSwitch))+
  xlab("RT (ms)") +
  ggtitle("RT distribution")

ggplot(data, aes(x = RT, fill = respModal)) +
  geom_histogram(binwidth = 0.1, position = "dodge") +
  #geom_density(alpha = 0.2, fill = "#FF6666") + # Overlay with transparent density plot
  # geom_vline(aes(xintercept = mean(RT, na.rm = T)),
             # colour = "red", linetype = "dashed", size = 1) + 
  facet_grid(cols = vars(RepSwitch))+
  xlab("RT (ms)") +
  ggtitle("RT distribution")

```


```{r}
type <- readxl::read_xlsx("D:\\GitHub\\experiment1\\Analysis\\pilot00\\pilot00_coded_updated.xlsx", sheet = 1) %>% 
  filter(Accuracy == 1) %>% 
  filter(RepSwitch %in% c("switch", "repeat"),
         respModal %in% c ("type")) %>% 
  mutate(RT = as.numeric(RT))
```

```{r}
min(type$RT)
max(type$RT)
```

```{r}
RTtype <- ggplot(type, aes(x = RT)) +
  geom_histogram(binwidth = 0.1,
                 colour = "black", fill = "white") +
  #geom_density(alpha = 0.2, fill = "#FF6666") + # Overlay with transparent density plot
  geom_vline(aes(xintercept = mean(RT, na.rm = T)),
             colour = "red", linetype = "dashed", size = 1) +
  xlab("RT type (ms)") +
  ggtitle("RT distribution of Type trials")

RTtype
```



```{r}
t.test(Mean_RT ~ Condition, data = data)
```

```{r}
t.test(Mean_RT ~ Modality, data = data)
```

```{r}
t.test(Mean_Duration ~ Condition, data = data)
```

```{r}
t.test(Mean_Duration ~ Modality, data = data)
```

