---
title: "Fillers_count"
author: "Katerina Tsaroucha"
date: "9/5/2023"
output: html_document
---


```{r}
rm(list = ls())
```


```{r}
df <- readxl::read_xlsx("C:\\Users\\Κατερίνα\\Nextcloud\\Experiment_1\\RF_Exp. 1\\List_Design.xlsx", sheet = 5)
```

```{r}
#Remove columns from dataset
df <- df[, -c(7:12)]

#Filter out break rows
df <- df[df$set != "BREAK",]
```

```{r}
# filter the data frame to include only target trials
df <- df[df$target != "NT",]

# filter the data frame to include only nontarget trials
df <- df[df$target != "T",]
```


```{r}
# create a new column called "prev_modality" based on the order of the trials
df$prev_modality <- c(NA, df$modality[-nrow(df)])

# create a new column called "next_modality" based on the order of the trials
library(dplyr)
df$next_modality <- lead(df$modality)
```

```{r}
# separate target trials from fillers
target_trials <- df[df$modality %in% c("speak", "type"),]
fillers <- df[df$modality %in% c("speak_filler", "type_filler"),]
```

```{r}
# separate nontarget trials from fillers
nt_trials <- df[df$modality %in% c("speak", "type"),]
fillers <- df[df$modality %in% c("speak_filler", "type_filler"),]
```

```{r}
# group each dataframe by trial type
# target_groups <- split(target_trials, target_trials$modality)
nt_groups <- split(nt_trials, nt_trials$modality)
filler_groups <- split(fillers, fillers$modality)
```

```{r}
# count the number of trials in each group
# target_counts <- lapply(target_groups, nrow)
nt_counts <- lapply(nt_groups, nrow)
filler_counts <- lapply(filler_groups, nrow)
```

```{r}
# print or visualize the results
cat("Target trials:\n")
#print(target_counts)
print(nt_counts)
cat("Fillers:\n")
print(filler_counts)
```

```{r}
# create four separate data frames for each of the four scenarios you want to analyze
speak_t_filler_follow_speak_t <- df[df$modality == "speak" & df$prev_modality == "speak" & df$target == "F",]
speak_t_filler_follow_type_t <- df[df$modality == "type" & df$prev_modality == "speak" & df$target == "F",]
type_t_filler_follow_speak_t <- df[df$modality == "speak" & df$prev_modality == "type" & df$target == "F",]
type_t_filler_follow_type_t <- df[df$modality == "type" & df$prev_modality == "type" & df$target == "F",]

# count the number of rows in each data frame to get the number of trials in each scenario
n_speak_t_filler_follow_speak_t <- nrow(speak_t_filler_follow_speak_t)
n_speak_t_filler_follow_type_t <- nrow(speak_t_filler_follow_type_t)
n_type_t_filler_follow_speak_t <- nrow(type_t_filler_follow_speak_t)
n_type_t_filler_follow_type_t <- nrow(type_t_filler_follow_type_t)
```

```{r}
print(n_speak_t_filler_follow_speak_t)
print(n_speak_t_filler_follow_type_t)
print(n_type_t_filler_follow_speak_t)
print(n_type_t_filler_follow_type_t)
```



```{r}
# create four separate data frames for each of the four scenarios you want to analyze
speak_filler_before_speak_nt <- df[df$modality == "speak" & df$target == "F" & df$next_modality == "speak" & df$repSwitch == "nontarget", ]

speak_filler_before_type_nt <- df[df$modality == "speak" & df$target == "F" & df$next_modality == "type" & df$repSwitch == "nontarget", ]

type_filler_before_speak_nt <- df[df$modality == "type" & df$target == "F" & df$next_modality == "speak" & df$repSwitch == "nontarget", ]

type_filler_before_type_nt <- df[df$modality == "type" & df$target == "F" & df$next_modality == "type" & df$repSwitch == "nontarget", ]
```


```{r}
# count the number of rows in each data frame to get the number of trials in each scenario
n_speak_filler_before_speak_nt <- nrow(speak_filler_before_speak_nt)
n_speak_filler_before_type_nt <- nrow(speak_filler_before_type_nt)
n_type_filler_before_speak_nt <- nrow(type_filler_before_speak_nt)
n_type_filler_before_type_nt <- nrow(type_filler_before_type_nt)
```

```{r}
print(n_speak_filler_before_speak_nt)
print(n_speak_filler_before_type_nt)
```

```{r}
print(n_type_filler_before_speak_nt)
print(n_type_filler_before_type_nt)
```

