---
title: "Fake_graphs"
author: "Katerina Tsaroucha"
date: "30/5/2023"
output: html_document
---

```{r}
library(xlsx)
library(ggplot2)
library(readr)
```

```{r}
data <- readxl::read_xlsx("C:\\Users\\Κατερίνα\\Nextcloud\\Experiment_1\\RF_Exp. 1\\Fake_graphs.xlsx", sheet = 1)
```

```{r}
ggplot(data, aes(x = Modality, y = MeanRT, fill = Condition)) + 
  geom_bar(colour = "black", stat = "identity", width = 0.5, position = "dodge") +
  scale_fill_brewer(palette = "Set1") +
  labs(x ='Modality', y='Mean RTs (ms)', title = 'Predicted values of modality across conditions')
```

```{r}
ggplot(data = data, aes(x = Condition, y = MeanRT, group = Modality, colour = Modality)) + 
  scale_color_manual(values=c('red', 'blue')) +
  geom_line(aes(group = Modality)) + 
  geom_point() 

```

```{r}
ggp <- ggplot(data)  + 
  geom_bar(aes(x = Condition, y = MeanRT, fill = Modality),stat="identity", width = 0.5, position = "dodge") +
  scale_fill_brewer(palette = "Set1") +
  geom_line(aes(x = Condition, y = MeanRT, group = Modality, colour = Modality),stat = "identity") +
  scale_color_manual(values=c('red', 'blue'))
  labs(title= "Predicted values of modality across conditions",
       x = "Condition", y = "Mean RTs (ms)")
  
ggp
```

```{r}
baseline <- readxl::read_xlsx("C:\\Users\\Κατερίνα\\Nextcloud\\Experiment_1\\RF_Exp. 1\\Fake_graphs.xlsx", sheet = 2)
```

```{r}
baseline <- ggplot(baseline, aes(x = Condition, y = MeanRT, fill = Modality)) + 
  geom_bar(colour = "black", stat = "identity", width = 0.5, position = "dodge") +
  scale_fill_brewer(palette = "Set1") +
  labs(x ='Condition', y='Mean RTs (ms)', title = 'Predicted values of modality across conditions') +
  theme_classic() +
  theme(plot.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.border = element_blank()
  )

baseline
```

